---
# docker-compose for Socorro development.
#
# Note: Requires docker-comopse 1.10+.
version: "2"
services:
  # Socorro app image
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: local/socorro_stackwalker_app
    env_file:
      - my.env
    volumes:
      - .:/app
